# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

highlighter: pygments

# Site settings
title: 0xSuu's Blog
email: hs1145@york.ac.uk
description: "Weibo: 0xSuu"
baseurl: ""
url: "http://0xsuu.me" # the base hostname & protocol for your site
twitter_username: 0xSuu
github_username:  al1enSuu
weibo_username: 0xSuu

# Build settings
markdown: kramdown
